### ISSUE TITLE
Falscher Film

### ISSUE THREAD

**Issue by dezi** [dezi/xavaro#4]
Hallo Patrick,

auf RTL 2 wurde gestern anstatt Hellboy der Marvel Film um 20:15 angezeigt. Vorher ist das Wetter mit einer Minute.

http://epg.xavaro.de/epgdata/tv/de/RTL%202%20Deutschland/2016.03.22.json.gz

Da läuft beim Verschmelzen etwas falsch.

**Comment by patrickzyolo** [comment]
Fixed.
