### ISSUE TITLE
WebLib Wiki

### ISSUE THREAD

**Issue by dezi** [dezi/xavaro#5]
Patrick, Du könntest mal den Wikipedia View in ein WebLibs Modul outsourcen. Das kann ich auch für andere Sachen benutzen.

Gruss
Dennis

**Comment by patrickz98** [comment]
Ist die Weblib Wiki nach deinen Vorstellungen? P.S das back Event must du selber auslösen da es in der Util.js ist, habe die aber eine Nuke function gegeben.
